package cs3500.controller;

import static org.junit.jupiter.api.Assertions.assertEquals;

import cs3500.controller.PlayGame;
import java.io.IOException;
import java.io.StringReader;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class PlayGameTest {

  String perfectGame = "6 6\n "
      + "3 1 1 1\n "
      + "0 0\n 0 1\n 0 2\n 0 3\n 0 4\n 0 5\n "
      + "1 0\n 1 1\n 1 2\n 1 3\n 1 4\n 1 5\n "
      + "2 0\n 2 1\n 2 2\n 2 3\n 2 4\n 2 5\n "
      + "3 0\n 3 1\n 3 2\n 3 3\n 3 4\n 3 5\n "
      + "4 0\n 4 1\n 4 2\n 4 3\n 4 4\n 4 5\n "
      + "5 0\n 5 1\n 5 2\n 5 3\n 5 4\n 5 5\n";

  String invalidBoardSize = "0 1\n 56 76\n 7 56\n 7 1\n a\n 6 6\n"
      + "3 1 1 1\n "
      + "0 0\n 0 1\n 0 2\n 0 3\n 0 4\n 0 5\n "
      + "1 0\n 1 1\n 1 2\n 1 3\n 1 4\n 1 5\n "
      + "2 0\n 2 1\n 2 2\n 2 3\n 2 4\n 2 5\n "
      + "3 0\n 3 1\n 3 2\n 3 3\n 3 4\n 3 5\n "
      + "4 0\n 4 1\n 4 2\n 4 3\n 4 4\n 4 5\n "
      + "5 0\n 5 1\n 5 2\n 5 3\n 5 4\n 5 5\n";

  String invalidFleetSize = "6 6\n "
      + "3 1 1 0\n a\n 3 1 1 2\n 0 1 1 1\n 1 0 1 1\n 1 1 0 1\n3 1 1 1\n "
      + "0 0\n 0 1\n 0 2\n 0 3\n 0 4\n 0 5\n "
      + "1 0\n 1 1\n 1 2\n 1 3\n 1 4\n 1 5\n "
      + "2 0\n 2 1\n 2 2\n 2 3\n 2 4\n 2 5\n "
      + "3 0\n 3 1\n 3 2\n 3 3\n 3 4\n 3 5\n "
      + "4 0\n 4 1\n 4 2\n 4 3\n 4 4\n 4 5\n "
      + "5 0\n 5 1\n 5 2\n 5 3\n 5 4\n 5 5\n";

  String lostGame = "6 6\n "
      + "3 1 1 1\n "
      + "0 0\n 1 1\n 0 2\n 0 3\n 4 4\n 0 5\n "
      + "1 0\n 1 1\n 1 2\n 1 3\n 1 4\n 2 5\n "
      + "2 0\n 2 1\n 4 2\n 2 3\n 2 4\n 3 5\n "
      + "3 0\n 5 1\n 3 2\n 2 3\n 3 4\n 3 5\n "
      + "4 0\n 4 1\n 5 2\n 4 3\n 0 4\n"
      + "5 0\n 5 1\n 5 2\n 5 3\n"
      + "5 4\n";

  String tieGame = "6 6\n "
      + "3 1 1 1\n "
      + "0 0\n 0 1\n 0 2\n 0 3\n 0 4\n 5 5\n "
      + "1 0\n 1 1\n 1 2\n 1 3\n 1 4\n 2 5\n "
      + "2 0\n 2 1\n 4 2\n 2 3\n 2 4\n 3 5\n "
      + "3 0\n 5 1\n 3 2\n 5 3\n 3 4\n 0 5\n "
      + "5 3\n 1 5\n 2 2\n 4 0\n 4 1\n"
      + "4 3\n 4 4\n 4 5\n 5 4\n"
      + "3 1\n 5 0\n 5 3\n"
      + "5 2\n"
      + "3 3\n";

  String invalidShot = "6 6\n "
      + "3 1 1 1\n "
      + "0 0\n 0 1\n 0 2\n 0 3\n 0 4\n 0 5\n "
      + "0 0\n 0 1\n 36 2\n a\n 6 7\n -1 2\n 2 -1\n"
      + "1 0\n 1 1\n 1 2\n 1 3\n 1 4\n 1 5\n "
      + "2 0\n 2 1\n 2 2\n 2 3\n 2 4\n 2 5\n "
      + "3 0\n 3 1\n 3 2\n 3 3\n 3 4\n 3 5\n "
      + "4 0\n 4 1\n 4 2\n 4 3\n 4 4\n 4 5\n "
      + "5 0\n 5 1\n 5 2\n 5 3\n 5 4\n 5 5\n";

  String perfectGameResponse = "Hello! Welcome to the OOD BattleSalvo Game!\n"
      + "Please enter a height and width between 6 and 15 below:\n"
      + "____________________________________________________________\n"
      + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine]. \n"
      + "Remember, your fleet may not exceed size 6.\n"
      + "____________________________________________________________\n"
      + "computer's board:\n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + "User's board:\n"
      + " -  C  -  -  C  C \n"
      + " B  C  D  -  C  C \n"
      + " B  C  D  -  C  C \n"
      + " B  C  D  S  C  C \n"
      + " B  C  D  S  C  C \n"
      + " B  C  -  S  C  C \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + "User's board:\n"
      + " -  C  -  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  H  S  C  C \n"
      + " B  H  D  S  C  C \n"
      + " H  C  -  S  C  C \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  -  -  -  - \n"
      + " H  M  -  -  -  - \n"
      + " H  M  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + "User's board:\n" + " -  H  -  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  H  S  C  C \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  S  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  H  -  -  - \n"
      + " H  M  H  -  -  - \n"
      + " H  M  H  -  -  - \n"
      + " H  H  H  -  -  - \n"
      + " H  H  H  -  -  - \n"
      + " H  H  H  -  -  - \n"
      + "User's board:\n"
      + " M  H  -  -  H  H \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  H \n"
      + " B  H  H  S  C  C \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  S  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n" + "computer's board:\n"
      + " H  M  H  M  -  - \n"
      + " H  M  H  H  -  - \n"
      + " H  M  H  H  -  - \n"
      + " H  H  H  H  -  - \n"
      + " H  H  H  H  -  - \n"
      + " H  H  H  M  -  - \n"
      + "User's board:\n"
      + " M  H  -  -  H  H \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  H \n"
      + " B  H  H  H  C  H \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  H  M  M  - \n"
      + " H  M  H  H  H  - \n"
      + " H  M  H  H  H  - \n"
      + " H  H  H  H  H  - \n"
      + " H  H  H  H  H  - \n"
      + " H  H  H  M  H  - \n"
      + "User's board:\n"
      + " M  H  -  -  H  H \n"
      + " H  H  D  -  C  C \n"
      + " B  H  H  -  C  H \n"
      + " B  H  H  H  C  H \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "You win!";


  String invalidBoardSizeResponse = "Hello! Welcome to the OOD BattleSalvo Game!\n"
      + "Please enter a height and width between 6 and 15 below:\n"
      + "____________________________________________________________\n"
      + "Uh Oh! You've entered invalid board size.\n"
      + "Please enter a height and width between 6 and 15 below:\n"
      + "____________________________________________________________\n"
      + "Uh Oh! You've entered invalid board size.\n"
      + "Please enter a height and width between 6 and 15 below:\n"
      + "____________________________________________________________\n"
      + "Uh Oh! You've entered invalid board size.\n"
      + "Please enter a height and width between 6 and 15 below:\n"
      + "____________________________________________________________\n"
      + "Uh Oh! You've entered invalid board size.\n"
      + "Please enter a height and width between 6 and 15 below:\n"
      + "____________________________________________________________\n"
      + "Uh Oh! You've entered invalid board size.\n"
      + "Please enter a height and width between 6 and 15 below:\n"
      + "____________________________________________________________\n"
      + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine]. \n"
      + "Remember, your fleet may not exceed size 6.\n"
      + "____________________________________________________________\n"
      + "computer's board:\n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + "User's board:\n"
      + " -  C  -  -  C  C \n"
      + " B  C  D  -  C  C \n"
      + " B  C  D  -  C  C \n"
      + " B  C  D  S  C  C \n"
      + " B  C  D  S  C  C \n"
      + " B  C  -  S  C  C \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + "User's board:\n"
      + " -  C  -  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  H  S  C  C \n"
      + " B  H  D  S  C  C \n"
      + " H  C  -  S  C  C \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  -  -  -  - \n"
      + " H  M  -  -  -  - \n"
      + " H  M  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + "User's board:\n" + " -  H  -  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  H  S  C  C \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  S  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  H  -  -  - \n"
      + " H  M  H  -  -  - \n"
      + " H  M  H  -  -  - \n"
      + " H  H  H  -  -  - \n"
      + " H  H  H  -  -  - \n"
      + " H  H  H  -  -  - \n"
      + "User's board:\n"
      + " M  H  -  -  H  H \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  H \n"
      + " B  H  H  S  C  C \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  S  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n" + "computer's board:\n"
      + " H  M  H  M  -  - \n"
      + " H  M  H  H  -  - \n"
      + " H  M  H  H  -  - \n"
      + " H  H  H  H  -  - \n"
      + " H  H  H  H  -  - \n"
      + " H  H  H  M  -  - \n"
      + "User's board:\n"
      + " M  H  -  -  H  H \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  H \n"
      + " B  H  H  H  C  H \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  H  M  M  - \n"
      + " H  M  H  H  H  - \n"
      + " H  M  H  H  H  - \n"
      + " H  H  H  H  H  - \n"
      + " H  H  H  H  H  - \n"
      + " H  H  H  M  H  - \n"
      + "User's board:\n"
      + " M  H  -  -  H  H \n"
      + " H  H  D  -  C  C \n"
      + " B  H  H  -  C  H \n"
      + " B  H  H  H  C  H \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "You win!";

  String invalidFleetSizeResponse = "Hello! Welcome to the OOD BattleSalvo Game!\n"
      + "Please enter a height and width between 6 and 15 below:\n"
      + "____________________________________________________________\n"
      + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine]. \n"
      + "Remember, your fleet may not exceed size 6.\n"
      + "____________________________________________________________\n"
      + "Uh Oh! You've entered invalid fleet sizes.\n"
      + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine]. \n"
      + "Remember, your fleet may not exceed size 6.\n"
      + "____________________________________________________________\n"
      + "Uh Oh! You've entered invalid fleet sizes.\n"
      + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine]. \n"
      + "Remember, your fleet may not exceed size 6.\n"
      + "____________________________________________________________\n"
      + "Uh Oh! You've entered invalid fleet sizes.\n"
      + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine]. \n"
      + "Remember, your fleet may not exceed size 6.\n"
      + "____________________________________________________________\n"
      + "Uh Oh! You've entered invalid fleet sizes.\n"
      + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine]. \n"
      + "Remember, your fleet may not exceed size 6.\n"
      + "____________________________________________________________\n"
      + "Uh Oh! You've entered invalid fleet sizes.\n"
      + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine]. \n"
      + "Remember, your fleet may not exceed size 6.\n"
      + "____________________________________________________________\n"
      + "Uh Oh! You've entered invalid fleet sizes.\n"
      + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine]. \n"
      + "Remember, your fleet may not exceed size 6.\n"
      + "____________________________________________________________\n"
      + "computer's board:\n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + "User's board:\n"
      + " -  C  -  -  C  C \n"
      + " B  C  D  -  C  C \n"
      + " B  C  D  -  C  C \n"
      + " B  C  D  S  C  C \n"
      + " B  C  D  S  C  C \n"
      + " B  C  -  S  C  C \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + "User's board:\n"
      + " -  C  -  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  H  S  C  C \n"
      + " B  H  D  S  C  C \n"
      + " H  C  -  S  C  C \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  -  -  -  - \n"
      + " H  M  -  -  -  - \n"
      + " H  M  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + "User's board:\n" + " -  H  -  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  H  S  C  C \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  S  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  H  -  -  - \n"
      + " H  M  H  -  -  - \n"
      + " H  M  H  -  -  - \n"
      + " H  H  H  -  -  - \n"
      + " H  H  H  -  -  - \n"
      + " H  H  H  -  -  - \n"
      + "User's board:\n"
      + " M  H  -  -  H  H \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  H \n"
      + " B  H  H  S  C  C \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  S  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n" + "computer's board:\n"
      + " H  M  H  M  -  - \n"
      + " H  M  H  H  -  - \n"
      + " H  M  H  H  -  - \n"
      + " H  H  H  H  -  - \n"
      + " H  H  H  H  -  - \n"
      + " H  H  H  M  -  - \n"
      + "User's board:\n"
      + " M  H  -  -  H  H \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  H \n"
      + " B  H  H  H  C  H \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  H  M  M  - \n"
      + " H  M  H  H  H  - \n"
      + " H  M  H  H  H  - \n"
      + " H  H  H  H  H  - \n"
      + " H  H  H  H  H  - \n"
      + " H  H  H  M  H  - \n"
      + "User's board:\n"
      + " M  H  -  -  H  H \n"
      + " H  H  D  -  C  C \n"
      + " B  H  H  -  C  H \n"
      + " B  H  H  H  C  H \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "You win!";


  String invalidShotResponse = "Hello! Welcome to the OOD BattleSalvo Game!\n"
      + "Please enter a height and width between 6 and 15 below:\n"
      + "____________________________________________________________\n"
      + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine]. \n"
      + "Remember, your fleet may not exceed size 6.\n"
      + "____________________________________________________________\n"
      + "computer's board:\n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + "User's board:\n"
      + " -  C  -  -  C  C \n"
      + " B  C  D  -  C  C \n"
      + " B  C  D  -  C  C \n"
      + " B  C  D  S  C  C \n"
      + " B  C  D  S  C  C \n"
      + " B  C  -  S  C  C \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + "User's board:\n"
      + " -  C  -  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  H  S  C  C \n"
      + " B  H  D  S  C  C \n"
      + " H  C  -  S  C  C \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "Uh Oh! You've entered an invalid shot.\n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "Uh Oh! You've entered an invalid shot.\n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "Uh Oh! You've entered an invalid shot.\n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "Uh Oh! You've entered an invalid shot.\n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "Uh Oh! You've entered an invalid shot.\n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  -  -  -  - \n"
      + " H  M  -  -  -  - \n"
      + " H  M  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + "User's board:\n" + " -  H  -  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  H  S  C  C \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  S  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  H  -  -  - \n"
      + " H  M  H  -  -  - \n"
      + " H  M  H  -  -  - \n"
      + " H  H  H  -  -  - \n"
      + " H  H  H  -  -  - \n"
      + " H  H  H  -  -  - \n"
      + "User's board:\n"
      + " M  H  -  -  H  H \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  H \n"
      + " B  H  H  S  C  C \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  S  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n" + "computer's board:\n"
      + " H  M  H  M  -  - \n"
      + " H  M  H  H  -  - \n"
      + " H  M  H  H  -  - \n"
      + " H  H  H  H  -  - \n"
      + " H  H  H  H  -  - \n"
      + " H  H  H  M  -  - \n"
      + "User's board:\n"
      + " M  H  -  -  H  H \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  H \n"
      + " B  H  H  H  C  H \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  H  M  M  - \n"
      + " H  M  H  H  H  - \n"
      + " H  M  H  H  H  - \n"
      + " H  H  H  H  H  - \n"
      + " H  H  H  H  H  - \n"
      + " H  H  H  M  H  - \n"
      + "User's board:\n"
      + " M  H  -  -  H  H \n"
      + " H  H  D  -  C  C \n"
      + " B  H  H  -  C  H \n"
      + " B  H  H  H  C  H \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "You win!";

  String lostGameResponse = "Hello! Welcome to the OOD BattleSalvo Game!\n"
      + "Please enter a height and width between 6 and 15 below:\n"
      + "____________________________________________________________\n"
      + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine]. \n"
      + "Remember, your fleet may not exceed size 6.\n"
      + "____________________________________________________________\n"
      + "computer's board:\n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + "User's board:\n"
      + " -  C  -  -  C  C \n"
      + " B  C  D  -  C  C \n"
      + " B  C  D  -  C  C \n"
      + " B  C  D  S  C  C \n"
      + " B  C  D  S  C  C \n"
      + " B  C  -  S  C  C \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  -  -  -  -  - \n"
      + " -  M  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " -  -  -  -  H  - \n"
      + " H  -  -  -  -  - \n"
      + "User's board:\n"
      + " -  C  -  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  H  S  C  C \n"
      + " B  H  D  S  C  C \n"
      + " H  C  -  S  C  C \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  -  -  -  - \n"
      + " -  M  -  -  -  - \n"
      + " H  M  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + " -  H  -  -  H  - \n"
      + " H  -  H  -  -  - \n"
      + "User's board:\n"
      + " M  H  -  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  H  S  C  C \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  S  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  H  -  -  - \n"
      + " -  M  H  -  -  - \n"
      + " H  M  -  -  H  - \n"
      + " H  H  H  -  -  - \n"
      + " -  H  H  -  H  - \n"
      + " H  -  H  M  -  - \n"
      + "User's board:\n"
      + " M  H  -  -  H  H \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  H \n"
      + " B  H  H  H  C  H \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  H  M  -  - \n"
      + " -  M  H  -  -  H \n"
      + " H  M  -  H  H  - \n"
      + " H  H  H  -  -  - \n"
      + " -  H  H  H  H  - \n"
      + " H  -  H  M  -  - \n"
      + "User's board:\n"
      + " M  H  M  M  H  H \n"
      + " H  H  D  -  C  C \n"
      + " B  H  H  -  C  H \n"
      + " H  H  H  H  C  H \n"
      + " B  H  H  S  C  C \n"
      + " H  H  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 5 shots.\n"
      + "computer's board:\n"
      + " H  M  H  M  M  - \n"
      + " -  M  H  -  H  H \n"
      + " H  M  -  H  H  H \n"
      + " H  H  H  -  H  - \n"
      + " H  H  H  H  H  - \n"
      + " H  -  H  M  -  - \n"
      + "User's board:\n"
      + " M  H  M  M  H  H \n"
      + " H  H  D  M  H  H \n"
      + " B  H  H  M  C  H \n"
      + " H  H  H  H  C  H \n"
      + " B  H  H  H  C  C \n"
      + " H  H  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 4 shots.\n"
      + "computer's board:\n"
      + " H  M  H  M  M  H \n"
      + " -  M  H  -  H  H \n"
      + " H  M  -  H  H  H \n"
      + " H  H  H  -  H  H \n"
      + " H  H  H  H  H  - \n"
      + " H  -  H  M  -  - \n"
      + "User's board:\n"
      + " M  H  M  M  H  H \n"
      + " H  H  H  M  H  H \n"
      + " H  H  H  M  C  H \n"
      + " H  H  H  H  H  H \n"
      + " H  H  H  H  C  H \n"
      + " H  H  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 1 shots.\n"
      + "You lose!";

  String tieGameResponse = "Hello! Welcome to the OOD BattleSalvo Game!\n"
      + "Please enter a height and width between 6 and 15 below:\n"
      + "____________________________________________________________\n"
      + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine]. \n"
      + "Remember, your fleet may not exceed size 6.\n"
      + "____________________________________________________________\n"
      + "computer's board:\n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + " -  -  -  -  -  - \n"
      + "User's board:\n"
      + " -  C  -  -  C  C \n"
      + " B  C  D  -  C  C \n"
      + " B  C  D  -  C  C \n"
      + " B  C  D  S  C  C \n"
      + " B  C  D  S  C  C \n"
      + " B  C  -  S  C  C \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " H  -  -  -  -  - \n"
      + " -  -  -  -  -  H \n"
      + "User's board:\n"
      + " -  C  -  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  H  S  C  C \n"
      + " B  H  D  S  C  C \n"
      + " H  C  -  S  C  C \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  -  -  -  - \n"
      + " H  M  -  -  -  - \n"
      + " H  M  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + " H  H  -  -  -  - \n"
      + " -  -  H  -  -  H \n"
      + "User's board:\n"
      + " M  H  -  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  C \n"
      + " B  H  H  S  C  C \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  S  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  H  -  -  - \n"
      + " H  M  H  -  -  - \n"
      + " H  M  -  -  H  - \n"
      + " H  H  H  -  -  - \n"
      + " H  H  H  -  -  - \n"
      + " -  -  H  M  -  H \n"
      + "User's board:\n"
      + " M  H  -  -  H  H \n"
      + " B  H  D  -  C  C \n"
      + " B  H  D  -  C  H \n"
      + " B  H  H  H  C  H \n"
      + " B  H  H  S  C  C \n"
      + " H  C  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 6 shots.\n"
      + "computer's board:\n"
      + " H  M  H  M  -  - \n"
      + " H  M  H  -  -  H \n"
      + " H  M  -  H  H  - \n"
      + " H  H  H  -  -  H \n"
      + " H  H  H  H  -  - \n"
      + " H  -  H  M  -  H \n"
      + "User's board:\n"
      + " M  H  M  M  H  H \n"
      + " H  H  D  -  C  C \n"
      + " B  H  H  -  C  H \n"
      + " H  H  H  H  C  H \n"
      + " B  H  H  S  C  C \n"
      + " H  H  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 5 shots.\n"
      + "computer's board:\n"
      + " H  M  H  M  M  - \n"
      + " H  M  H  -  H  H \n"
      + " H  M  H  H  H  - \n"
      + " H  H  H  -  -  H \n"
      + " H  H  H  H  -  - \n"
      + " H  H  H  M  -  H \n"
      + "User's board:\n"
      + " M  H  M  M  H  H \n"
      + " H  H  D  M  H  H \n"
      + " B  H  H  M  C  H \n"
      + " H  H  H  H  C  H \n"
      + " B  H  H  H  C  C \n"
      + " H  H  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 4 shots.\n"
      + "computer's board:\n"
      + " H  M  H  M  M  - \n"
      + " H  M  H  -  H  H \n"
      + " H  M  H  H  H  - \n"
      + " H  H  H  -  H  H \n"
      + " H  H  H  H  H  H \n"
      + " H  H  H  M  H  H \n"
      + "User's board:\n"
      + " M  H  M  M  H  H \n"
      + " H  H  D  M  H  H \n"
      + " B  H  H  M  C  H \n"
      + " H  H  H  H  H  H \n"
      + " H  H  H  H  C  H \n"
      + " H  H  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 3 shots.\n"
      + "computer's board:\n"
      + " H  M  H  M  M  H \n"
      + " H  M  H  H  H  H \n"
      + " H  M  H  H  H  - \n"
      + " H  H  H  -  H  H \n"
      + " H  H  H  H  H  H \n"
      + " H  H  H  M  H  H \n"
      + "User's board:\n"
      + " M  H  M  M  H  H \n"
      + " H  H  H  M  H  H \n"
      + " H  H  H  M  C  H \n"
      + " H  H  H  H  H  H \n"
      + " H  H  H  H  C  H \n"
      + " H  H  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 1 shots.\n"
      + "computer's board:\n"
      + " H  M  H  M  M  H \n"
      + " H  M  H  H  H  H \n"
      + " H  M  H  H  H  M \n"
      + " H  H  H  -  H  H \n"
      + " H  H  H  H  H  H \n"
      + " H  H  H  M  H  H \n"
      + "User's board:\n"
      + " M  H  M  M  H  H \n"
      + " H  H  H  M  H  H \n"
      + " H  H  H  M  C  H \n"
      + " H  H  H  H  H  H \n"
      + " H  H  H  H  H  H \n"
      + " H  H  M  H  H  H \n"
      + "Please enter a shot in the form \"X Y\". You have 1 shots.\n"
      + "You tied!";
  StringBuilder sb = new StringBuilder();

  PlayGame pgPerfect;
  PlayGame pgInvalidSize;
  PlayGame pgInvalidFleet;
  PlayGame pgInvalidShot;

  PlayGame pgLost;

  PlayGame pgTie;

  @BeforeEach
  void setUp() {
    pgPerfect = new PlayGame(new StringReader(perfectGame), sb, 4);
    pgInvalidSize = new PlayGame(new StringReader(invalidBoardSize), sb, 4);
    pgInvalidFleet = new PlayGame(new StringReader(invalidFleetSize), sb, 4);
    pgInvalidShot = new PlayGame(new StringReader(invalidShot), sb, 4);
    pgLost = new PlayGame(new StringReader(lostGame), sb, 4);
    pgTie = new PlayGame(new StringReader(tieGame), sb, 4);
  }

  @Test
  void runPerfect() throws IOException {
    pgPerfect.run();
    assertEquals(perfectGameResponse, sb.toString());
  }

  @Test
  void runInvalidSize() throws IOException {
    pgInvalidSize.run();
    assertEquals(invalidBoardSizeResponse, sb.toString());
  }

  @Test
  void runInvalidFleet() throws IOException {
    pgInvalidFleet.run();
    assertEquals(invalidFleetSizeResponse, sb.toString());
  }

  @Test
  void runInvalidShot() throws IOException {
    pgInvalidShot.run();
    assertEquals(invalidShotResponse, sb.toString());
  }

  @Test
  void runLost() throws IOException {
    pgLost.run();
    assertEquals(lostGameResponse, sb.toString());
  }

  @Test
  void runTie() throws IOException {
    PlayGame pgTie = new PlayGame(new StringReader(tieGame), sb, 4);
    pgTie.run();
    assertEquals(tieGameResponse, sb.toString());
  }
}